#!/usr/bin/env bash

#./build

if [ $? -ne 0 ]
then
  echo "BUILD FAILED - NOT DEPLOYING"
  exit 1
fi
 d
git checkout gh-pages

git checkout master -- deployFileList

cat deployFileList | xargs --max-args=1 git checkout master --

#this line will require manual intervention to add a comment
git commit

#this line will require username and password
git push

git checkout master
