#!/usr/bin/env bash

if [ "$1" == "-f" ]
then
  #./build -f
  echo "FAST DEPLOY"
else
  ./build
fi

if [ $? -ne 0 ]
then
  echo "BUILD FAILED - NOT DEPLOYING"
  exit 1
fi

DEST=/var/www/html/TSP

rm -r $DEST/*

cat deployFileList | xargs -I{} cp -v {} $DEST

